config/routes.rb
Rails.application.routes.draw do
 root 'people#index'

 resources :people do
 	resources :animals
 end
end

app/models/animal.rb
class Animal < ApplicationRecord
	validates_presence_of :name, :species

	belongs_to :person
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
	# validations
	validates_presence_of :name

	# callbacks
		# after_create - runs once after model is created
		# before_create - runs once before model is created
		# after_save - runs each time after a model is saved
		# before_save - runs each time before a model is saved
		# after_initialize - runs once after a Person.new instance
		# before_initialize - runs before instance gets created in memory
		# after_validiate - runs after all of the validations
		# before_validate - runs before all validations

	# associations
		# has_one
		# has_many
		# belongs_to
		# has_many_through
		# has_one_through
	has_many :animals, dependent: :destroy

	# instance methods
	def info
		"#{name} is of age: #{age}"
	end

	# class methods -or- scopes, have 'self.'
	#can be combined: Person.all.by_name.by_age
	
	# to call: Person.all.by_name
	def self.by_name
		order(:name)
	end

	# Person.all.by_age
	def by_age
		order(:age)
	end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_person
  before_action :set_animal, except: [:index, :new, :create]

  def index
  	@animals = @person.animals
  end

  def show
  end

  def new
  	@animal = @person.animals.new
  end

  def create
  	@animal = @person.animals.new(animal_params)
  	if @animal.save
  		redirect_to person_animal_path(@person, @animal)
  	else
  	end
  end

  def edit
  end

  def update
  	if @animal.update(animal_params)
  		redirect_to person_animal_path(@person, @animal)
  	else
  		render :edit
  	end
  end

  def destroy
  	@animal.destroy
  	redirect_to person_animals_path(@person)
  end

  private

  def animal_params
  	params.require(:animal).permit(:name, :age, :alive, :species)
  end

  def set_person
  	@person = Person.find(params[:person_id])
  end

  def set_animal
  		@animal = @person.animals.find(params[:id])
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # before_action :set_person, only: [:show, :edit, :update, :destroy] # this code is long
   before_action :set_person, except: [:index, :new, :create]


  def index
  	@people = Person.all.by_name
  end

  def show
  end

  def new
  	@person = Person.new
  end

  def create
  	@person = Person.new(person_params)
  	if @person.save
  		redirect_to person_path(@person)
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @person.update(person_params)
  		redirect_to person_path(@person)
  	else
  		render :edit
  	end
  end

  def destroy
  	@person.destroy
  	redirect_to people_path
  end

  private

  	def person_params
  		params.require(:person).permit(:name, :age,
  																	 :gender, :alive)
  	end

  	def set_person
  		@person = Person.find(params[:id])
  	end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/animals/_form.html.erb
<%= form_for [@person, @animal] do |f| %>
	<%= f.label :name %>:
	<%= f.text_field :name, required: true %>
	<br>
	
	<%= f.label :species %>:
	<%= f.text_field :species, required: true %>
	<br>

	<%= f.label :age %>:
	<%= f.number_field :age %>
	<br>
	
	<%= f.label :alive %>:
	<%= f.check_box :alive %>
	<br>
	
	<%= f.submit %>
<% end %>

app/views/animals/edit.html.erb
<h1>Edit Animal For <%= @person.name %> </h1>
<hr>

<%= render(partial: 'form') %> 

app/views/animals/index.html.erb
<h1> All Animals For: <%= @person.name %> </h1>
<hr>

<% if @animals.any? %>
	<% @animals.each do |animal| %>
		<div>
		<%= link_to animal.name, person_animal_path(@person, animal) %> - 
		<%= link_to 'Edit', edit_person_animal_path(@person, animal) %> | 
		<%= link_to 'Delete', person_animal_path(@person, animal), method: :delete,
			data:{confirm: 'Are you sure you want to remove this animal?'}	 %>
		</div>
	<% end %>
<% else %>
	<h4> <%= @person.name %> doesn't have any animals. </h4>
<% end %>

<br>

<%= link_to 'Add New Animal >>', new_person_animal_path(@person) %>

<br><br>
<hr><br>

<%= link_to '<< Back to Person Page', person_path(@person) %>

app/views/animals/new.html.erb
<h1>New Animal For <%= @person.name %> </h1>
<hr>

<%= render(partial: 'form') %> 

app/views/animals/show.html.erb
<h1> <%= @animal.name %> </h1>
<hr>
<h3> Belongs to <%= @person.name %> </h3>

<div>
		<h4>Species: <%= @animal.species %></h4>

	<% if @animal.age %>
		<h4>Age: <%= @animal.age %></h4>
	<% end %>

	<h4>Alive: <%= @animal.alive ? 'Yes' : 'No' %></h4>
</div>

<hr><br>

<%= link_to "<< Back To #{@person.name}'s Animals", person_animals_path(@person) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalsRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_person_form.html.erb
<% if @person.errors.any? %>
	<h5> <%= pluralize(@person.errors.count, 'Error', 'Errors') %> Creating Person </h5>
	<ul>
	<% @person.errors.full_messages.each do |message| %>
		<li> <%= message %> </li>
	</ul>
	<% end %>
<% end %>

<%= form_for @person do |f| %>
	<%= f.label :name %>:
	<%= f.text_field :name, required: true %>
	<br>
	
	<%= f.label :age %>:
	<%= f.text_field :age %>
	<br>
	
	<%= f.label :gender %>:
	<%= f.text_field :gender %>
	<br>
	
	<%= f.label :alive %>:
	<%= f.radio_button :alive, true %> Yes
	<%= f.radio_button :alive, false %> No
	<br>
	
	<%= f.submit 'Submit' %>
<% end %>

app/views/people/edit.html.erb
<h1>
	Edit Person
	<%= @person.name %>
</h1>
<hr>

<%= render(partial: 'person_form') %>

<hr>

<%= link_to '<< Cancel', people_path %>

app/views/people/index.html.erb
<h1>List of People</h1>
<hr>

<% if @people.any? %>
	<ul>
		<% @people.each do |person| %>
			<li>
			<%= link_to person.name, person_path(person) %> - 
			<%= link_to 'Edit', edit_person_path(person) %> | 
			<%= link_to 'Delete', person_path(person), method: :delete,
				data:{confirm: 'Are you sure you want to delete this person?'}	 %>
			</li>
		<% end %>
	</ul>
<% else %>
	<h3>No People Found</h3>
<% end %>

<hr>

<%= link_to 'Add Person', new_person_path %>

app/views/people/new.html.erb
<h1>Add Person</h1>
<hr>

<%= render(partial: 'person_form') %> 

app/views/people/show.html.erb
<h1>
	<%= @person.name %>
</h1>
<hr>

<div>
	<% if @person.age %>
		<h4>Age: <%= @person.age %></h4>
	<% end %>

	<% if @person.gender %>
		<h4>Gender: <%= @person.gender %></h4>
	<% end %>

	<h4>Alive: <%= @person.alive ? 'Yes' : 'No' %></h4>
</div>

<%= link_to "#{@person.name}'s Animals >>", person_animals_path(@person) %>

<br><br>
<hr><br>

<%= link_to '<< Back To All People', people_path %>